In [5]:
import pandas as pd
import root_pandas as rpd
import numpy as np

In [6]:
inputDir="/eos/user/m/musella/data/mod_dep_004"
fname = inputDir+"/output_InsideAcceptance_125.root"
trees = map(lambda x: "genDiphotonDumper/trees/InsideAcceptance_125_13TeV_SigmaMpTTag_%d" %x, xrange(3))
branch = "scaleWeights"
branches = [branch,"weight"]

dataframes = map(lambda x: rpd.read_root(fname,x,columns=branches,flatten=True), trees )

In [7]:
for x in dataframes: x[branch]=x[branch]*x["weight"]

In [8]:
percat = map(lambda y: np.array(map(lambda x: x[1][branch].sum(), y.groupby("__array_index")) ), dataframes)
percat

[array([  9.3178365 ,   9.51321148,   9.0858994 ,   7.91217547,
          8.0750964 ,   7.70409956,  11.04061833,  11.28181939,  10.77781381]),
 array([ 11.67982376,  11.94631802,  11.36800762,   9.92682237,
         10.15140808,   9.64436999,  13.82640559,  14.14928804,  13.4804493 ]),
 array([ 19.52887613,  19.98475753,  19.00288488,  16.6265976 ,
         16.99989448,  16.16141365,  23.07625937,  23.65060076,  22.46857318])]

In [9]:
total = sum(percat)
total

array([ 40.5265364 ,  41.44428703,  39.45679191,  34.46559544,
        35.22639896,  33.5098832 ,  47.94328329,  49.08170818,  46.72683628])

In [10]:
relative = map(lambda x: x/total, percat)
relative

[array([ 0.22991939,  0.22954217,  0.23027466,  0.22956735,  0.22923423,
         0.22990529,  0.23028499,  0.22985792,  0.23065576]),
 array([ 0.28820187,  0.28825006,  0.28811282,  0.28802121,  0.28817615,
         0.28780673,  0.28839088,  0.28828027,  0.2884948 ]),
 array([ 0.48187874,  0.48220778,  0.48161252,  0.48241144,  0.48258962,
         0.48228797,  0.48132414,  0.48186181,  0.48084944])]

In [11]:
def sumsq(x):
    return np.sqrt(np.sum(np.square(x))-np.square(np.sum(x))/x.size)/np.mean(x)

map(sumsq, relative)

[0.0054003726712440678, 0.0019830619952448626, 0.0032821566871246276]

In [14]:
sumsq(total)

0.40969838057917268

In [16]:
def maxdev(x):
    return np.max(np.abs(x-np.mean(x)))/np.mean(x)

map(maxdev, relative)

[0.0032185985879676087, 0.0013394572087955048, 0.0021624212941473769]

In [17]:
maxdev(total)

0.19912533250430714