In [1]:
import pandas as pd
import root_pandas as rpd
import numpy as np

Welcome to JupyROOT 6.07/07


In [41]:
inputDir="/eos/user/m/musella/data/mod_dep_004"
fname = inputDir+"/output_InsideAcceptance_125.root"
trees = map(lambda x: "genDiphotonDumper/trees/InsideAcceptance_125_13TeV_SigmaMpTTag_%d" %x, xrange(3))

alphaSWeights = map(lambda x: rpd.read_root(fname,x,columns=["alphaSWeights","weight"],flatten=True), trees )
scaleWeights = map(lambda x: rpd.read_root(fname,x,columns=["scaleWeights","weight"],flatten=True), trees )
pdfWeights = map(lambda x: rpd.read_root(fname,x,columns=["pdfWeights","weight"],flatten=True), trees )


frames = [(alphaSWeights,"alphaSWeights"),(scaleWeights,"scaleWeights"),(pdfWeights,"pdfWeights")]

In [42]:
def scale(x):
    frames,name = x
    for x in frames: x[name]=x[name]*x["weight"]
        
map(scale,frames)

[None, None, None]

In [43]:
percat = map(lambda z:
                 (map(lambda y: 
                    np.array(map(lambda x: x[1][z[1]].sum(), y.groupby("__array_index")) ), z[0]),z[1]), frames)
percat

[([array([ 9.13563706,  9.4431973 ]),
   array([ 11.4519006 ,  11.83587758]),
   array([ 19.14301121,  19.79796013])],
  'alphaSWeights'),
 ([array([  9.3178365 ,   9.51321148,   9.0858994 ,   7.91217547,
            8.0750964 ,   7.70409956,  11.04061833,  11.28181939,  10.77781381]),
   array([ 11.67982376,  11.94631802,  11.36800762,   9.92682237,
           10.15140808,   9.64436999,  13.82640559,  14.14928804,  13.4804493 ]),
   array([ 19.52887613,  19.98475753,  19.00288488,  16.6265976 ,
           16.99989448,  16.16141365,  23.07625937,  23.65060076,  22.46857318])],
  'scaleWeights'),
 ([array([ 9.31558459,  9.31528762,  9.29991102,  9.31388142,  9.32099398,
           9.31667   ,  9.30266927,  9.32795443,  9.30747529,  9.30942146,
           9.31953067,  9.34484222,  9.33968332,  9.33790034,  9.33471684,
           9.31593092,  9.29624211,  9.30591632,  9.29721115,  9.30477175,
           9.28578688,  9.35853425,  9.31009282,  9.33983179,  9.30111462,
           9.33542144,

In [44]:
total = map(lambda x: (sum(x[0]),x[1]), percat)
total

[(array([ 39.73054887,  41.07703501]), 'alphaSWeights'),
 (array([ 40.5265364 ,  41.44428703,  39.45679191,  34.46559544,
          35.22639896,  33.5098832 ,  47.94328329,  49.08170818,  46.72683628]),
  'scaleWeights'),
 (array([ 40.51547777,  40.5211642 ,  40.46721978,  40.50974283,
          40.52786554,  40.51371249,  40.45621793,  40.5582032 ,
          40.49905005,  40.51092427,  40.53100126,  40.62172362,
          40.61379796,  40.61571373,  40.58766066,  40.528513  ,
          40.44499892,  40.5071496 ,  40.44780301,  40.46985218,
          40.42144757,  40.67637938,  40.50031929,  40.61705295,
          40.4477161 ,  40.59210347,  40.57837622,  40.56149396,
          40.58944506,  40.23520264,  40.40122234,  40.61586963,
          40.48121516,  40.54027562,  40.57842167,  40.50710694,
          40.56629145,  40.60053447,  40.40322545,  40.68101421,
          40.62226266,  40.45663433,  40.58618464,  40.4514165 ,
          40.57632828,  40.67819125,  40.54088947,  40.56742634

In [45]:
relative = map(lambda y: (map(lambda x: x/y[1][0], y[0][0]),y[0][1]), zip(percat,total) )
relative

[([array([ 0.22993987,  0.22988994]),
   array([ 0.28823917,  0.28813856]),
   array([ 0.48182096,  0.4819715 ])],
  'alphaSWeights'),
 ([array([ 0.22991939,  0.22954217,  0.23027466,  0.22956735,  0.22923423,
           0.22990529,  0.23028499,  0.22985792,  0.23065576]),
   array([ 0.28820187,  0.28825006,  0.28811282,  0.28802121,  0.28817615,
           0.28780673,  0.28839088,  0.28828027,  0.2884948 ]),
   array([ 0.48187874,  0.48220778,  0.48161252,  0.48241144,  0.48258962,
           0.48228797,  0.48132414,  0.48186181,  0.48084944])],
  'scaleWeights'),
 ([array([ 0.22992656,  0.22988697,  0.22981344,  0.22991707,  0.22998976,
           0.22996337,  0.22994412,  0.22998934,  0.2298196 ,  0.22980027,
           0.22993586,  0.23004544,  0.22996331,  0.22990856,  0.22998903,
           0.22986116,  0.22984899,  0.22973516,  0.22985701,  0.2299186 ,
           0.22972425,  0.23007294,  0.22987702,  0.22994853,  0.22995401,
           0.22998122,  0.22991656,  0.23003425,  0.2

In [46]:
def sumsq(x):
    return np.sqrt(np.sum(np.square(x))-np.square(np.sum(x))/x.size)/np.mean(x)

map(lambda x: (map(sumsq, x[0]),x[1]), relative )

[([0.00015353217369893537, 0.0002468775105159739, 0.00022089130052722729],
  'alphaSWeights'),
 ([0.0054003726712440678, 0.0019830619952448626, 0.0032821566871246276],
  'scaleWeights'),
 ([0.0028438228085656651, 0.0022982775783370428, 0.0026990354762462805],
  'pdfWeights')]

In [47]:
map(lambda x: (sumsq(x[0]),x[1]), total)

[(0.023564854544721719, 'alphaSWeights'),
 (0.40969838057917268, 'scaleWeights'),
 (0.01527099421853889, 'pdfWeights')]

In [48]:
def maxdev(x):
    return np.max(np.abs(x-np.mean(x)))/np.mean(x)

map(lambda x: (map(maxdev, x[0]),x[1]), relative )

[([0.00010856364164376621, 0.0001745687612828987, 0.00015619373629043582],
  'alphaSWeights'),
 ([0.0032185985879676087, 0.0013394572087955048, 0.0021624212941473769],
  'scaleWeights'),
 ([0.00091587662677541633, 0.00083486761364214349, 0.0009362416600032106],
  'pdfWeights')]

In [49]:
map(lambda x: (maxdev(x[0]),x[1]), total)

[(0.016662868446245874, 'alphaSWeights'),
 (0.19912533250430714, 'scaleWeights'),
 (0.0072648402275026112, 'pdfWeights')]